# Generated by Django 4.2.21 on 2025-05-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='test_t',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
