# Generated by Django 4.2.21 on 2025-05-12 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_test_t'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='test_t',
        ),
    ]
