# Generated by Django 4.2.21 on 2025-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_remove_product_test_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'ของใช้ทั่วไป'), ('CLOTHING', 'เครื่องแต่งกาย'), ('KITCHEN', 'เครื่องครัว'), ('PLANT', 'ต้นไม้')], default='GENERAL', help_text='หมวดหมู่ของสินค้า', max_length=20),
        ),
    ]
