# Generated by Django 4.2.20 on 2025-05-01 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0005_product_price_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbon_reduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='จำนวนคาร์บอนที่ลดได้ (กิโลกรัม)', max_digits=6),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='shopapp.product')),
            ],
        ),
    ]
