# Generated by Django 4.2.20 on 2025-05-03 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_remove_product_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_info', to='shopapp.product'),
        ),
    ]
