# Generated by Django 4.2.20 on 2025-05-03 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_saleinformation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinformation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_informations', to='shopapp.product'),
        ),
    ]
