# Generated by Django 4.2.21 on 2025-05-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcontent_sustainableproduct_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL วิดีโอ (YouTube, Vimeo)'),
        ),
        migrations.AlterField(
            model_name='blogcontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='รูปภาพประกอบ (ถ้ามี)'),
        ),
    ]
