# Generated by Django 4.2.21 on 2025-05-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcontent_video_url_alter_blogcontent_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SustainableProduct',
        ),
        migrations.AddField(
            model_name='blogcontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='blog_videos/', verbose_name='ไฟล์วิดีโอ MP4'),
        ),
    ]
