# Generated by Django 4.2.21 on 2025-05-09 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '__first__'),
        ('cart', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'option')},
        ),
    ]
