# Generated by Django 4.2.21 on 2025-05-12 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopapp', '0004_product_category'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='ชื่อผู้รับ', max_length=100)),
                ('province', models.CharField(default='จังหวัด', max_length=100)),
                ('district', models.CharField(default='อำเภอ', max_length=100)),
                ('sub_district', models.CharField(default='ตำบล/เขต', max_length=100)),
                ('postal_code', models.CharField(default='00000', max_length=10)),
                ('address_detail', models.TextField(default='บ้านเลขที่/หมู่บ้าน/ถนน')),
                ('note', models.TextField(blank=True, default='')),
                ('phone_number', models.CharField(default='0000000000', max_length=15)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_carbon_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROCESSING', 'กำลังดำเนินการ'), ('SHIPPED', 'จัดส่งแล้ว'), ('DELIVERED', 'ส่งถึงแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'รอการชำระเงิน'), ('COMPLETED', 'ชำระเงินแล้ว'), ('FAILED', 'การชำระเงินล้มเหลว')], default='PENDING', max_length=20)),
                ('promptpay_id', models.CharField(blank=True, max_length=13, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.address')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.productoption')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shopapp.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
