# Generated by Django 4.2.21 on 2025-05-13 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'รอชำระเงิน'), ('COMPLETED', 'ชำระเงินแล้ว')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='promptpay_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROCESSING', 'กำลังดำเนินการ'), ('SHIPPED', 'จัดส่งแล้ว'), ('DELIVERED', 'จัดส่งสำเร็จ'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_carbon_reduction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
