# Generated by Django 4.2.21 on 2025-05-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.AddField(
            model_name='address',
            name='address_detail',
            field=models.TextField(default='บ้านเลขที่/หมู่บ้าน/ถนน'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='อำเภอ', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.CharField(default='จังหวัด', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='sub_district',
            field=models.CharField(default='ตำบล/เขต', max_length=100),
        ),
    ]
