# Generated by Django 4.2.21 on 2025-05-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_address_address_line_remove_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'รอการชำระเงิน'), ('COMPLETED', 'ชำระเงินแล้ว'), ('FAILED', 'การชำระเงินล้มเหลว')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='promptpay_id',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
